/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Referensi;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class FormJual extends javax.swing.JFrame {

    /**
     * Creates new form FormJual
     */
    PenjualanController controller;
    public FormJual() {
        initComponents();
        controller = new PenjualanController(this);
        controller.isiCboPelanggan();
        controller.clearFormFaktur();
        controller.clearFormBarang();
        controller.clearFormHasil();
    }
    public JTable getTblRinciJual() {
        return TblRinciJual;
    }

    public javax.swing.JComboBox<String> getCboPelanggan() {
        return cboPelanggan;
    }
   

    public javax.swing.JTextField gettxtDiskon() {
        return txtDiskon;
    }
    
     public javax.swing.JTextField gettxtHarga() {
        return txtHarga;
    }

    public javax.swing.JTextField gettxtJumlah() {
        return txtJumlah;
    }

    public javax.swing.JTextField gettxtKodeBarang() {
        return txtKodeBarang;
    }

    public javax.swing.JTextField gettxtNamabarang(){
        return txtNamabarang;
    }
    
    public javax.swing.JTextField gettxtNoFaktur() {
        return txtNoFaktur;
    }

    public javax.swing.JTextField gettxtTanggal() {
        return txtTanggal;
    }

    public javax.swing.JTextField gettxtTotal() {
        return txtTotal;
    }

    public javax.swing.JTextField gettxtTotalBayar() {
        return txtTotalBayar;
    }

    public javax.swing.JTextField gettxtTotalDiskon() {
        return txtTotalDiskon;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNoFaktur = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRinciJual = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtTotalDiskon = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        txtJumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtNamabarang = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        cboPelanggan = new javax.swing.JComboBox<>();
        btnDeleteFaktur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("No Faktur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 55, 16);

        jLabel2.setText("Pelanggan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 59, 16);

        jLabel3.setText("Tanggal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 80, 16);

        txtNoFaktur.setText("1");
        getContentPane().add(txtNoFaktur);
        txtNoFaktur.setBounds(200, 20, 310, 22);

        jTextField2.setText("jTextField1");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 20, 310, 22);
        getContentPane().add(txtTanggal);
        txtTanggal.setBounds(200, 120, 310, 22);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari);
        btnCari.setBounds(600, 20, 55, 25);

        jLabel4.setText("Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 210, 80, 16);

        TblRinciJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                " Kode Barang", "Nama Barang", "Jumlah", "Harga", "Diskon", "Total"
            }
        ));
        TblRinciJual.setAutoscrolls(false);
        TblRinciJual.setColumnSelectionAllowed(true);
        TblRinciJual.setShowHorizontalLines(false);
        TblRinciJual.setShowVerticalLines(false);
        jScrollPane1.setViewportView(TblRinciJual);
        TblRinciJual.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 300, 950, 140);

        jLabel5.setText("Total");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 520, 29, 16);

        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 570, 37, 16);

        jLabel7.setText("Total Bayar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 620, 65, 16);

        txtTotal.setText("jTextField4");
        getContentPane().add(txtTotal);
        txtTotal.setBounds(170, 520, 220, 22);

        txtTotalDiskon.setText("jTextField5");
        getContentPane().add(txtTotalDiskon);
        txtTotalDiskon.setBounds(170, 570, 220, 22);

        txtTotalBayar.setText("jTextField6");
        getContentPane().add(txtTotalBayar);
        txtTotalBayar.setBounds(170, 620, 220, 22);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(550, 560, 90, 50);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(710, 560, 100, 50);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(880, 560, 100, 50);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(880, 210, 100, 25);

        txtJumlah.setText("jTextField10");
        getContentPane().add(txtJumlah);
        txtJumlah.setBounds(520, 250, 160, 22);

        jLabel8.setText("Nama Barang");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 210, 100, 16);

        jLabel9.setText("Harga");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 210, 80, 16);

        jLabel10.setText("Jumlah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(560, 210, 60, 16);

        jLabel11.setText("Diskon");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(730, 210, 37, 16);

        txtKodeBarang.setText("jTextField3");
        txtKodeBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeBarangKeyPressed(evt);
            }
        });
        getContentPane().add(txtKodeBarang);
        txtKodeBarang.setBounds(30, 250, 140, 22);

        txtHarga.setText("jTextField1");
        getContentPane().add(txtHarga);
        txtHarga.setBounds(350, 250, 170, 22);

        txtNamabarang.setText("jTextField1");
        getContentPane().add(txtNamabarang);
        txtNamabarang.setBounds(170, 250, 180, 22);

        txtDiskon.setText("jTextField1");
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(680, 250, 130, 22);

        cboPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(cboPelanggan);
        cboPelanggan.setBounds(200, 70, 310, 22);

        btnDeleteFaktur.setText("Delete");
        btnDeleteFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFakturActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteFaktur);
        btnDeleteFaktur.setBounds(880, 250, 100, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeBarangKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            controller.onKeyPressKodeBarang();
        }
    }//GEN-LAST:event_txtKodeBarangKeyPressed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        controller.onClickBtnInsert();
        controller.viewTabelRinciJual();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.onClickBtnDelete();
        controller.viewTabelRinciJual();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        controller.onClickBtnSimpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        controller.onClickBtnCari();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.onClickBtnUpdate();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFakturActionPerformed
        // TODO add your handling code here:
       controller.onClickBtnDeleteFaktur();
    }//GEN-LAST:event_btnDeleteFakturActionPerformed

    private void cboPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblRinciJual;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteFaktur;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamabarang;
    private javax.swing.JTextField txtNoFaktur;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtTotalDiskon;
    // End of variables declaration//GEN-END:variables

    Object gettxtNamaBarang() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
